<h1>1_Numpy </h1>

In [1]:
import numpy as np
np.__version__

'1.23.2'

In [2]:
arr_1 = np.array([1,2,3,4,5,6,7,8,9,0])

In [3]:
display(arr_1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [4]:
display(type(arr_1))

numpy.ndarray

In [5]:
arr_1.dtype

dtype('int64')

In [6]:
arr_1.itemsize

8

In [7]:
arr_1.shape

(10,)

In [8]:
print(arr_1.ndim)

1


In [9]:
arr_1.nbytes

80

In [10]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([1,2,3,4,5,6,7,8,9])
print(a+b)

[ 2  4  6  8 10 12 14 16 18]


In [11]:
display(a*b)

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [12]:
a**b

array([        1,         4,        27,       256,      3125,     46656,
          823543,  16777216, 387420489])

In [13]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [15]:
char_arr = np.array(['kunal','rushi','omkar','mahesh','harsh'],dtype='str')

In [16]:
display(char_arr)

array(['kunal', 'rushi', 'omkar', 'mahesh', 'harsh'], dtype='<U6')

In [17]:
char_arr.dtype

dtype('<U6')

In [18]:
char_arr.itemsize

24

In [19]:
x = np.array([1,2,3,4,5,6,7,8,9])
y = np.array([10,12,13,14,15,16,17,18,19])

In [20]:
display(x+y)

array([11, 14, 16, 18, 20, 22, 24, 26, 28])

In [21]:
display(x*y)

array([ 10,  24,  39,  56,  75,  96, 119, 144, 171])

In [22]:
display(x**y)

array([                  1,                4096,             1594323,
                 268435456,         30517578125,       2821109907456,
           232630513987207,   18014398509481984, 1350851717672992089])

In [23]:
display(x/y)

array([0.1       , 0.16666667, 0.23076923, 0.28571429, 0.33333333,
       0.375     , 0.41176471, 0.44444444, 0.47368421])

In [24]:
display(x//y)

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
import time
import numpy as np

vector_size = 1000000

def python_version():
    t1 = time.time()
    x = range(1000000)
    y = range(1000000)
    z = [x[i]+y[i] for i in range(len(x))]
    return time.time() - t1

def numpy_version():
    t1 = time.time()
    x = np.arange(vector_size)
    y = np.arange(vector_size)
    z = x+y
    return time.time()-t1

t1 = python_version()
t2 = numpy_version()

display(t1)
display(t2)
print("Numpy in this example is : " + str(t1/t2) + " Faster")

0.20261406898498535

0.005593061447143555

Numpy in this example is : 36.22596871136877 Faster


In [26]:
k = list(range(10))
l = list(range(10))

In [27]:
k

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [28]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [29]:
k+l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

<h4>Types of Numpy Array</h4>

In [30]:
arr_1 = np.array([0,10,20,30,40,50,60,55])

In [31]:
arr_2 = np.array([[99,18,19,14,55,66,22,40],
                 [98,26,27,28,34,39,43,21]])

In [32]:
display(arr_1)
display(arr_2)

array([ 0, 10, 20, 30, 40, 50, 60, 55])

array([[99, 18, 19, 14, 55, 66, 22, 40],
       [98, 26, 27, 28, 34, 39, 43, 21]])

In [33]:
arr_1.shape

(8,)

In [34]:
arr_2.shape

(2, 8)

In [35]:
arr_1.itemsize

8

In [36]:
arr_2.itemsize

8

In [37]:
arr_2.ndim

2

In [38]:
arr_1.ndim

1

In [39]:
arr_1[5]

50

In [40]:
arr_2[1,5]

39

In [41]:
arr_2[1,7]

21

In [42]:
arr_2[-1,-1]

21

In [43]:

arr_1

array([ 0, 10, 20, 30, 40, 50, 60, 55])

In [44]:
arr_2

array([[99, 18, 19, 14, 55, 66, 22, 40],
       [98, 26, 27, 28, 34, 39, 43, 21]])

In [45]:
arr_2[1,6] = 666

In [46]:
arr_2

array([[ 99,  18,  19,  14,  55,  66,  22,  40],
       [ 98,  26,  27,  28,  34,  39, 666,  21]])

In [47]:
arr_2.dtype

dtype('int64')

In [48]:
arr_3 = np.array([ [[1,2,3,4,5,6],
                    [7,8,9,10,11,12],
                    [11,22,33,44,55,66]],

                   [[12,23,34,45,56,67],
                    [21,32,43,54,65,76],
                    [31,42,53,64,75,86]]])

In [49]:
arr_3

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [11, 22, 33, 44, 55, 66]],

       [[12, 23, 34, 45, 56, 67],
        [21, 32, 43, 54, 65, 76],
        [31, 42, 53, 64, 75, 86]]])

In [50]:
arr_3

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [11, 22, 33, 44, 55, 66]],

       [[12, 23, 34, 45, 56, 67],
        [21, 32, 43, 54, 65, 76],
        [31, 42, 53, 64, 75, 86]]])

In [51]:
arr_3.dtype

dtype('int64')

In [52]:
arr_3.ndim

3

In [53]:
arr_3.shape

(2, 3, 6)

In [54]:
arr_4 = np.array([11,23,34,57,79,28,64])

In [55]:
arr_4

array([11, 23, 34, 57, 79, 28, 64])

In [56]:
arr_4[0]

11

In [57]:
arr_4.dtype

dtype('int64')

In [58]:
arr_4.itemsize

8

In [59]:
arr_4.shape

(7,)

In [60]:
arr_4.ndim

1

In [61]:
arr_4[4]=11.22

In [62]:
arr_4

array([11, 23, 34, 57, 11, 28, 64])

In [63]:
arr_5 = arr_4.astype('float')

In [64]:
arr_5

array([11., 23., 34., 57., 11., 28., 64.])

In [65]:
arr_4

array([11, 23, 34, 57, 11, 28, 64])

In [66]:
arr_5.dtype

dtype('float64')

In [67]:
arr_6 = np.empty(8, dtype = 'float32')

In [68]:
arr_6

array([0.00000e+00, 0.00000e+00, 2.86285e-42, 1.83674e-40, 1.45735e-43,
       1.45735e-43, 2.24208e-44, 0.00000e+00], dtype=float32)

In [69]:
arr_6.fill(232)

In [70]:
arr_6

array([232., 232., 232., 232., 232., 232., 232., 232.], dtype=float32)

In [71]:
arr_6.dtype

dtype('float32')

In [72]:
arr_7 = np.arange(16)

In [73]:
arr_7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [74]:
arr_7[::-1]

array([15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [75]:
arr_7[5:10]

array([5, 6, 7, 8, 9])

In [76]:
arr_7[1:10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
arr_8 = np.arange(1,101)

In [78]:
arr_8

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [79]:
arr_9 = arr_8.reshape(10,10)

In [80]:
arr_9

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [81]:
np.flipud(arr_9)

array([[ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10]])

In [82]:
np.fliplr(arr_9)

array([[ 10,   9,   8,   7,   6,   5,   4,   3,   2,   1],
       [ 20,  19,  18,  17,  16,  15,  14,  13,  12,  11],
       [ 30,  29,  28,  27,  26,  25,  24,  23,  22,  21],
       [ 40,  39,  38,  37,  36,  35,  34,  33,  32,  31],
       [ 50,  49,  48,  47,  46,  45,  44,  43,  42,  41],
       [ 60,  59,  58,  57,  56,  55,  54,  53,  52,  51],
       [ 70,  69,  68,  67,  66,  65,  64,  63,  62,  61],
       [ 80,  79,  78,  77,  76,  75,  74,  73,  72,  71],
       [ 90,  89,  88,  87,  86,  85,  84,  83,  82,  81],
       [100,  99,  98,  97,  96,  95,  94,  93,  92,  91]])

In [83]:
arr_10 = np.ones((3,6), dtype = 'int16')

In [84]:
arr_10

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int16)

In [85]:
arr_zeros = np.zeros((4,4),dtype = 'float')

In [86]:
arr_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [87]:
arr_ones = np.ones((4,4),dtype = 'float')

In [88]:
arr_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [89]:
arr_indentity = np.identity(10)

In [90]:
arr_indentity

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [91]:
np.identity(8, dtype = 'int')

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [92]:
np.empty(6)

array([0.0e+000, 2.5e-323, 0.0e+000, 0.0e+000, 0.0e+000, 0.0e+000])

In [93]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [94]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [95]:
np.linspace(1,10,12).reshape(4,3)

array([[ 1.        ,  1.81818182,  2.63636364],
       [ 3.45454545,  4.27272727,  5.09090909],
       [ 5.90909091,  6.72727273,  7.54545455],
       [ 8.36363636,  9.18181818, 10.        ]])

In [96]:
np.logspace(1,1,6, base = 10)

array([10., 10., 10., 10., 10., 10.])

In [97]:
arr = np.ones((10,10))
arr[1:-1,1:-1]=0

In [98]:
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [99]:
arr_12 = np.zeros((10,10))
arr_12[1::2,::2] = 1
arr_12[::2,1::2]=1
arr_12

array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.]])

In [100]:
arr_13 = np.array([[1,2,3],[4,5,6]])

In [101]:
arr_13

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
arr_13.sum()

21

In [103]:
arr_13.sum(axis=0)

array([5, 7, 9])

In [104]:
arr_13.sum(axis=1)

array([ 6, 15])

In [105]:
arr_13.min()

1

In [106]:
arr_13.max()

6

In [107]:
arr_13.min(axis=0)

array([1, 2, 3])

In [108]:
arr_13.max(axis=1)

array([3, 6])

In [109]:
arr_14 = np.array([1,2,3,4,56,33,6,9])
np.argmax(arr_14)

4

In [110]:
np.argmin(arr_14)

0

In [111]:
arr_13.ravel()

array([1, 2, 3, 4, 5, 6])

In [112]:
arr_15 = np.array([[5,2,8],[6,1,9]])
arr_15

array([[5, 2, 8],
       [6, 1, 9]])

In [113]:
arr_15.mean()

5.166666666666667

In [114]:
arr_15.mean(axis=0)

array([5.5, 1.5, 8.5])

In [115]:
arr_15.mean(axis=1)

array([5.        , 5.33333333])

In [116]:
arr_15.std()

2.9107081994288304

In [117]:
arr_15.std(axis=0)

array([0.5, 0.5, 0.5])

In [118]:
arr_15.std(axis=1)

array([2.44948974, 3.29983165])

In [119]:
arr_15.var()

8.472222222222223

In [120]:
arr_15.var(axis=0)

array([0.25, 0.25, 0.25])

In [121]:
arr_15.var(axis=1)

array([ 6.        , 10.88888889])

In [122]:
arr_16 = np.array([1.24,2.66,1.2,9,44])

In [123]:
arr_16.round()

array([ 1.,  3.,  1.,  9., 44.])

In [124]:
x = np.ones((4,1))

In [125]:
y = np.ones((3,))

In [126]:
x

array([[1.],
       [1.],
       [1.],
       [1.]])

In [127]:
y

array([1., 1., 1.])

In [128]:
y.reshape(1,3)

array([[1., 1., 1.]])

In [129]:
x+y

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [130]:
a = np.ones((2,5))

In [131]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [132]:
b = np.ones((5,))

In [133]:
b

array([1., 1., 1., 1., 1.])

In [134]:
a+b

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [135]:
a = np.random.randint(10, 20,size = (3,5))

In [136]:
a

array([[16, 14, 14, 19, 10],
       [12, 10, 16, 11, 18],
       [10, 18, 18, 18, 17]])

In [137]:
b = np.ones(5)
b.reshape(5,1)
b

array([1., 1., 1., 1., 1.])

In [138]:
a+b

array([[17., 15., 15., 20., 11.],
       [13., 11., 17., 12., 19.],
       [11., 19., 19., 19., 18.]])

In [139]:
n = np.random.randint(10,50,size=(3,5))

In [140]:
n

array([[44, 22, 41, 29, 36],
       [33, 37, 25, 36, 42],
       [30, 11, 42, 35, 11]])

In [141]:
n.shape

(3, 5)

In [142]:
n.T

array([[44, 33, 30],
       [22, 37, 11],
       [41, 25, 42],
       [29, 36, 35],
       [36, 42, 11]])

In [143]:
n.T.shape

(5, 3)

In [144]:
n.flatten()

array([44, 22, 41, 29, 36, 33, 37, 25, 36, 42, 30, 11, 42, 35, 11])

In [145]:
n.ravel()

array([44, 22, 41, 29, 36, 33, 37, 25, 36, 42, 30, 11, 42, 35, 11])

<h1>End</h1>